### ISSUE TITLE
č se ne prikaže na grafih v poročilu

### ISSUE THREAD

**Issue by PrelogSasa** [PrelogSasa/APPR-2018-19#3]
Ko poženem poročilo se ponekod v naslovih grafov in v imenih osi ne pokažejo č-ji, čeprav ostali šumniki delajo. Na primer:
![slika](https://user-images.githubusercontent.com/39483287/52151350-17913e80-2673-11e9-8446-56c85791b1b8.PNG)
Čeprav imam v kodi napisan č:
https://github.com/PrelogSasa/APPR-2018-19/blob/e67ca23179a8618665afae33af4ebb4b474bd69f/projekt.Rmd#L88
 Kaj bi lahko bilo narobe?

**Comment by PrelogSasa** [comment]
Poskusila sem vse skupaj pognati na Binderju in tam pokaže vse č-je, sem pa opazila da mi odreže nekatere naslove in imena osi, ki so precej dolga. Kako pa lahko to popravim?

**Comment by jernejbanevec** [comment]
Meni se v tvojem poročilu pokažejo vsi šumniki, ti je torej ta problem morda uspelo odpraviti?
Imena grafov pa lahko razdeliš tako, da kar v ime grafa dopišeš `\n`. V kolikor imaš v mislih npr. graf z naslovom _Graf povezave med investiranjem v boljše ravnanje z odpadki in ločevanjem odpadkov za Savinjsko regijo_, lahko to ime grafa napišeš v več vrsticah, tako da vstaviš `\n` (torej znak za prelom vrstice) v sam naslov grafa. Torej v definiciji grafa lahko za naslov grafa prišteješ kar:
```R
+ ggtitle("Graf povezave med investiranjem v boljše ravnanje \n z odpadki in ločevanjem odpadkov za Savinjsko regijo")
```
in naslov grafa se bo prelomil na označenem mestu.

**Comment by PrelogSasa** [comment]
Hvala!
