### ISSUE TITLE
zaključek

### ISSUE THREAD

**Issue by PrelogSasa** [PrelogSasa/APPR-2018-19#4]
Zdaj počasi zaključujem projekt in bi rada prosila če ga lahko pregledate  in komentirate ali bi mogla še kaj popraviti. Hvala!

**Comment by jaanos** [comment]
Poročilo se prevede, tako da bom dodal povezavo na repozitorij za zagovore, z @alenFMF pa se lahko domeniš za termin zagovora, če se še nisi. Če boš še kaj spreminjala, mi prosim javi, da posodobim povezavo.

Imam pa sledeče pripombe:
* Razpredelnici `izobrazba.regije` in `starostne.skupine.regije` nista v obliki *tidy data*. Da bosta, spravi izobrazbe oziroma starostne skupine v svoj stolpec.
* Pri drugem grafu se ti na osi y pojavi eksponentna notacija. Da se ji izogneš, podatke deli s 1000 in ustrezno popravi oznako osi.
* Pri grafu za Savinjsko regijo ni jasno, v katero smer gre črta. Svetujem, da na graf dodaš oznake z letnicami - dovolj bo najbrž samo za prvo in zadnje leto, da se oznake spodaj levo ne bodo prekrivale.
* V Shiny aplikaciji za izbiro števila skupin namesto `numericInput` predlagam `sliderInput`, saj je sicer mogoče vnesti tudi neštevilske vrednosti, kar privede do napake.

**Comment by PrelogSasa** [comment]
Sem popravila, kar ste predlagali, tako da prosim posodobite povezavo na repozitoriju za zagovore. Me pa še zanima nekaj. Ena izmed tabel, ki sem jih na začetku uvozila, se je izkazala za precej neuporabno glede na to v kakšno smer sem šla s svojim projektom in je nakoncu nisem nikjer uporabila (za noben graf ali karkoli) in me zanima ali jo je sploh smiselno obdržati v poročilu (in datotki za uvoz) ali je boljše da jo kar pobrišem? Hvala!

**Comment by jaanos** [comment]
V redu, bom posodobil.

Kar se tiče neuporabljene razpredelnice, načeloma ni narobe, da jo uvoziš in prikažeš - lahko pa jo seveda tudi odstraniš. Če je pa ne odstraniš, lahko v poročilu omeniš, da je nisi nikjer uporabila.
